spring:
  application:
    name: '@name@'
    version: '@version@'

  elasticsearch:
    rest:
      uris: ${TWITTER_ELASTICSEARCH_HOSTS:localhost:9200}

management:
  metrics.export.graphite:
    host: ${GRAPHITE_HOST:localhost}
    port: ${GRAPHITE_PORT:2003}
    global-prefix: ${spring.application.name}
    protocol: PLAINTEXT
    step: 10s


server:
  port: ${SERVER_PORT:8083}

logging:
  level:
    io.twitterconsumer.service: DEBUG
