version: '3.7'

services:

# 3-node elasticsearch cluster
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    networks:
      - docker_twitter-network
      - default
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=elasticsearch,es02
#      - cluster.initial_master_nodes=elasticsearch,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es02
    networks:
      - docker_twitter-network
      - default
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch,es03
      - cluster.initial_master_nodes=elasticsearch,es02
#      - cluster.initial_master_nodes=elasticsearch,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

#  es03:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
#    container_name: es03
#    networks:
#      - docker_twitter-network
#      - default
#    environment:
#      - node.name=es03
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=elasticsearch,es02
#      - cluster.initial_master_nodes=elasticsearch,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.6.2
#    container_name: logstash
#    command: logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./config:/etc/logstash/conf.d
#    ports:
#      - "5000:5000"
#    depends_on:
#      - elasticsearch
#      - es02
#      - es03
#    networks:
#      - docker_twitter-network
#      - default
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.6.2
#    container_name: kibana
#    depends_on:
#      - elasticsearch
#      - es02
#      - es03
#    networks:
#      - docker_twitter-network
#      - default
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200


networks:
  docker_twitter-network:
    external: true
